musicaly:

  outputs:
    dev:
      dataset: musicaly_staging
      fixed_retries: 1
      keyfile: ../../gcp/google_credentials.json
      location: us-central1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID', 'musicaly-project') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery

    prod:
      dataset: musicaly_production
      fixed_retries: 1
      keyfile: ../../gcp/google_credentials.json
      location: us-central1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID', 'musicaly-project') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery

  target: dev